steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/firestore-cleanup-service:$COMMIT_SHA'
      - '.'
    id: 'Build Image'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/firestore-cleanup-service:$COMMIT_SHA'
    id: 'Push Image'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'firestore-cleanup-service'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/firestore-cleanup-service:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated' # Remove this if you want to require authentication
      - '--set-env-vars=DATABASE_ID=uploads'
      - '--memory=512Mi'
      - '--timeout=540' # 9 minutes timeout
      - '--max-instances=10'
    id: 'Deploy to Cloud Run'

  # 4. Create Cloud Scheduler job to trigger the service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Get the Cloud Run service URL
        SERVICE_URL=$(gcloud run services describe firestore-cleanup-service --region=${_REGION} --format='value(status.url)')
        
        # Delete existing job if it exists (ignore errors)
        gcloud scheduler jobs delete firestore-cleanup-job --location=${_REGION} --quiet || true
        
        # Create a new Cloud Scheduler job
        gcloud scheduler jobs create http firestore-cleanup-job \
          --location=${_REGION} \
          --schedule="0 * * * *" \
          --uri="$${SERVICE_URL}/" \
          --http-method=POST \
          --time-zone="Etc/UTC" \
          --attempt-deadline="540s"
    id: 'Create Scheduler Job'

# Define the images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/firestore-cleanup-service:$COMMIT_SHA'

# Define substitutions that can be passed in from the trigger
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: 'us-east5'
  _ARTIFACT_REGISTRY_REPO: 'cleanup-functions-repo'